// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqjhshssdmaqhhakimnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxamhzaHNzZG1hcWhoYWtpbW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzgwMjMsImV4cCI6MjA2OTgxNDAyM30.VIGzU-2WAHOx5_lx_rUgSE7Uktm2dZ2wuVF44ZO_msw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});